name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install protobuf-compiler
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Prepare artifact directory
      run: |
        mkdir -p dist
        cp target/release/semantrix dist/
        cp -r resources dist/
        cp config.yml dist/
        cp start.sh dist/

    - name: Create zip archive
      run: cd dist && zip -r ../artifact.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: artifact.zip
